# Generated by Django 4.1.6 on 2023-02-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tastTitle',
            new_name='taskTitle',
        ),
    ]
